Add controllers
UmkasArt/java-shareit pull request #1
Opened 2022-10-20 22:51 UTC by UmkasArt

2022-10-21 19:12 UTC, sergeymamonov requested changes

2022-10-21 19:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        //validateUser(userDto.toUser());
Закомментированный код необходимо удалить.

2022-10-21 19:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    private static long generatorId = 0;
Почему поле сделано статическим? Нужно чтобы из разных экземпляров этого класса был доступ к статическому полю? Если причин делать статическим нет, то лучше сделать экземпляром класса. В ItemRepositoryImpl аналогично.

2022-10-21 19:12 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new IllegalArgumentException();
Лучше добавить сообщение в ошибку. Потом будет легче разбирать логи и понимать происходящее.

2022-10-21 19:14 UTC, UmkasArt commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        //validateUser(userDto.toUser());
Исправлено

2022-10-21 19:15 UTC, UmkasArt commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    private static long generatorId = 0;
Исправлено

2022-10-21 19:20 UTC, UmkasArt commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new IllegalArgumentException();
Исправлено

2022-10-22 05:12 UTC, sergeymamonov approved these changes

2022-10-22 10:05 UTC, merged