Add docker
UmkasArt/java-shareit pull request #10
Opened 2022-12-03 13:24 UTC by UmkasArt

Выполнить ТЗ 17 спринта

2022-12-04 20:03 UTC, sergeymamonov requested changes
BookingServiceImpl строки 80-84 и ниже по коду, валидацию входных данных нужно сделать в  модуле gateway. Сюда уже приходят данные, прошедшие валидацию.

Если тело веток одинаково, то условия можно объединить через ||

2022-12-04 20:03 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        resp.put("error", String.format("Unknown state: UNSUPPORTED_STATUS"));
String.format() здесь избыточен

2022-12-04 20:03 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  class ItemServiceImpl implements ItemService {
Строки 78-82 и ниже по классу эта валидация должна быть в модуле gateway

2022-12-04 20:03 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
>          User user = userRepository.findById(userId)
Строки 45-51 и ниже по классу валидация, которая должна быть в модуле gateway.
Строки 52 и 87 создание лишней переменной.
Строки 59 и 81 а почему нельзя запрос в БД itemRepository сделать с in. И тогда будет один запрос, а не равное количеству элементов в itemRequestDtos

2022-12-04 20:03 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>              user.get().setName(userDto.getName());
Строки 45, 48, 50 можно получить ошибку, если user = =null. Посмотрите, про правильное использование get для Optional.

2022-12-04 20:40 UTC, UmkasArt commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  class ItemServiceImpl implements ItemService {
Исправлено

2022-12-04 21:03 UTC, UmkasArt commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        resp.put("error", String.format("Unknown state: UNSUPPORTED_STATUS"));
Исправлено

2022-12-04 21:09 UTC, UmkasArt commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
>          User user = userRepository.findById(userId)
45-51 исправлено
52 и 87 исправлено
59 и 81 не совсем понял замечание. У меня сейчас и так запрос, возвращающий лист итемреквестов на 60 строке и один итем реквест на 70-79. Не очень понимаю, как можно сделать запрос с in.

2022-12-04 21:09 UTC, UmkasArt commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>              user.get().setName(userDto.getName());
Исправил. Сделал посимпатичнее.

2022-12-05 19:24 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
>          User user = userRepository.findById(userId)
Метод setItemsToItemRequestDto содержит обращение к БД. Этот метод вызывается в цикле. Лучше постараться уйти от цикла и сделать минимальное количество запросов.

2022-12-05 19:28 UTC, sergeymamonov commented
Почему проект форкнут, а не сгенерирован?
BookingServiceImpl строки 80-84 и ниже по коду этого класса, валидацию входных данных нужно сделать в модуле gateway.

2022-12-05 19:44 UTC, UmkasArt commented
> 

Когда стартовал проект при переход к тз-1 репозиторий автоматически создается. Я уже не помню всех деталей, но тот репозиторий, который создается автоматически, я удалил. Случайно. В итоге пришлось искать способ, чтобы скопировать проект в свой репозиторий так, чтобы были чеки, была возможность создавать пулреквесты.
Сделал вот таким образом. (

2022-12-05 21:12 UTC, UmkasArt commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
>          User user = userRepository.findById(userId)
Что то я сразу не приметил, что в цикле вызывается метод, который селектит базу.
Поправил этот момент, написав кастомный метод.

2022-12-06 11:32 UTC, sergeymamonov commented
> > 
> 
> BookingServiceImpl строки 80-84 - исправлено.
> 
> Когда стартовал проект при переход к тз-1 репозиторий автоматически создается. Я уже не помню всех деталей, но тот репозиторий, который создается автоматически, я удалил. Случайно. В итоге пришлось искать способ, чтобы скопировать проект в свой репозиторий так, чтобы были чеки, была возможность создавать пулреквесты. Сделал вот таким образом, то есть форкнул (

Нужно обратиться к наставнику, он подскажет, что нужно сделать. Пока принять пулл реквест не могу.

2022-12-06 11:42 UTC, UmkasArt commented
> 

Сергей, я не очень понимаю, почему именно сейчас Вас этот вопрос заинтересовал. Репозиторий существует уже 8 недель и мы стабильно 3 спринта принимали у меня задания, о чем свидетельствуют пулреквесты. А теперь вы мне говорите, что то не так с репозиторием? 
Какая вообще разница, какой репозиторий.

2022-12-07 15:24 UTC, sergeymamonov approved these changes

2022-12-07 15:24 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            List<ItemShortDto> itemShortDtoList = itemsList.stream().filter(item -> item.getRequestId().equals(itemRequestDto.getId())).map(ItemMapper::toItemShortDto).collect(Collectors.toList());
Старайтесь не делать строки более 120 символов. Стримы часто пишут на каждой новой строке новый оператор, то есть 
.filter()
.map()
...

2022-12-07 17:24 UTC, merged