Add bookings
UmkasArt/java-shareit pull request #4
Opened 2022-11-05 22:09 UTC by UmkasArt

Переделать все на JPA. Добавить бронирования и комменты.

2022-11-05 23:02 UTC, UmkasArt commented
В тестах постмана была замечена ошибка.
В первоначальной версии сценарий такой:
создается первый пользователь. Затем второй. Но по каким то причинам, в ожидается что второй пользователь создаться с id = 3. Затем пользователь с id = 3 удаляется, создается еще один с id = 4. 
И дальше по ходу всех 163 тестов эта ошибка сохраняется. И кейсы сделаны с учетом этой ошибки.
Я поправил эту ошибку в файле sprint.json, но по каким то причинам мои изменения не учитываются. И падения начинаются на начиная с 6 теста с названием User Create. Ожидается, что вернется пользователь с id = 3.
![image](https://user-images.githubusercontent.com/98515293/200144610-bcf1ce8e-8a56-4f8b-a1d3-eb082123efda.png)
![image](https://user-images.githubusercontent.com/98515293/200144630-9baef824-d7b5-4461-854d-9c2b0236510a.png)

2022-11-06 21:49 UTC, sergeymamonov requested changes

2022-11-06 21:49 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
>      }
Можно еще добавить обработку рантайм ошибки.

2022-11-06 21:49 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +);
Можно добавить FOREIGN KEYS для сохранения целостности данных.

2022-11-06 23:00 UTC, UmkasArt commented on src/main/resources/schema.sql
> +);
Добавил

2022-11-06 23:01 UTC, UmkasArt commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
>      }
Добавил обработку исключения RuntimeException.
Не придумал какой HTTP код отдавать, поставил 500.

2022-11-07 13:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
>      }
Да, все верно.

2022-11-07 13:04 UTC, sergeymamonov approved these changes

2022-11-07 13:25 UTC, merged